//import { GeistSans, GeistMono } from "@geist-ui/react/font";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ContextProvider from './context'

// Font configuration changed in Next.js 14
//export const fontSans = GeistSans({
  //variable: "--font-geist-sans",
  //subsets: ["latin"],
//});


//export const fontMono = GeistMono({
  //variable: "--font-geist-mono",
  //subsets: ["latin"],
//});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className="antialiased">
        <ContextProvider>
          <Header />
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
