import { GeistSans, GeistMono } from "geist/font"; // Updated font import
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ContextProvider from './context'

// Font configuration changed in Next.js 14
export const fontSans = GeistSans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

<<<<<<< HEAD

=======
export const fontMono = GeistMono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
>>>>>>> 2d9fcac02e227db4a1bf9f3fcce579f9f5aba2e8

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fontSans.variable} ${fontMono.variable}`}>
      <body className="antialiased">
        <ContextProvider>
          <Header />
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
